# VMProbe
prefix=test
delay=5000
endpoint=/var/lib/node_exporter/textfile_collector/vms.prom
url=qemu:///system
perfhardware=PERF_COUNT_HW_INSTRUCTIONS,PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_BRANCH_MISSES,PERF_COUNT_HW_BRANCH_INSTRUCTIONS,PERF_COUNT_HW_CACHE_MISSES,PERF_COUNT_HW_CACHE_REFERENCES
perfsoftware=PERF_COUNT_SW_CONTEXT_SWITCHES,PERF_COUNT_SW_PAGE_FAULTS
perfhardwarecache=
# ids are kernel dependant, find them with cat /sys/kernel/debug/tracing/events/*/*/id 
perftracepoint=306,308,310